const data = [
    {
        brand: "Nike",
        genre: "Man",
        title: "Nike React Infinity Run Flyknit 3",
        price: 160,
        img: [
            `https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/5a28e397-d083-4398-b0d9-a9911ae22018/react-infinity-run-flyknit-3-zapatillas-de-running-carretera-Pp5hlk.png`,
            `https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/c44f5879-48c5-4b3a-a4a6-5274ed6c4dd7/react-infinity-run-flyknit-3-zapatillas-de-running-carretera-Pp5hlk.png`,
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/aff84436-35c5-4ecc-9774-a4638610fef3/react-infinity-run-flyknit-3-zapatillas-de-running-carretera-Pp5hlk.png",
        ],
        description:
            "Nuestras zapatillas más probadas, diseñadas para ayudarte a superar tras tus metas más altas metas de running. Las Nike React Infinity Run 3 ofrecen suavidad y estabilidad con una pisada agradable que te llevará por cualquier ruta, larga o corta. La parte superior transpirable está diseñada para ofrecer contención, sin perder flexibilidad. Incluso hemos añadido más amortiguación en el talón y el tobillo para proporcionar una sensación de sujeción. No dejes de correr, lo tiene todo.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Nike",
        genre: "Man",
        title: "Nike Air Zoom Pegasus 39",
        price: 120,
        img: [
            `https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/8b3be65e-eb8c-47b6-9813-1160a4400ec1/air-zoom-pegasus-39-zapatillas-de-running-asfalto-JNVFbf.png`,
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/c6fa0f18-c652-4310-a4ad-a5623c6c9744/air-zoom-pegasus-39-zapatillas-de-running-asfalto-JNVFbf.png",
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/246c656a-7bf0-4ef7-a96b-7a58dd9e0096/air-zoom-pegasus-39-zapatillas-de-running-asfalto-JNVFbf.png",
        ],
        description:
            "El running es tu ritual diario, y cada pisada te acerca a tus objetivos personales. Las Nike Air Zoom Pegasus 39 te hacen llegar a nuevas alturas al entrenar y correr con su diseño intuitivo. Son más ligeras en la parte superior que las Pegasus 38 e ideales para cualquier temporada, ofrecen sujeción y contención, y la amortiguación de la planta del pie combinada con unidades Zoom Air dobles (1 más que en las Peg 38) aportan un toque adicional a cada pisada. Vuelve un modelo todoterreno con alas. Es hora de volar.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Nike",
        genre: "Man",
        title: "Nike Winflo 8",
        price: 99,
        img: [
            `https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/7c2fff38-9f89-40f1-bbcf-ffbfaab5adbc/wio-8-zapatillas-de-running-asfalto-xNW8fz.png`,
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/58ad6844-01b5-41ac-a25c-70b8bec0a69b/wio-8-zapatillas-de-running-asfalto-xNW8fz.png",
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/4955a805-e528-47c1-9e4f-62ff242cba2d/wio-8-zapatillas-de-running-asfalto-xNW8fz.png",
        ],
        description:
            "Cuando corres todos los días, necesitas una sujeción que se adapte a tu velocidad. Las Nike Winflo 8 recuperan la amortiguación que más te gusta e incorporan detalles como la parte superior translúcida y la tecnología Flywire para ofrecer un ajuste ceñido y estable para las carreras largas sobre asfalto.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Nike",
        genre: "Man",
        title: "Nike Zoom Alphafly Next Nature",
        price: 299,
        img: [
            `https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/04993055-6221-4a74-8ff2-bd37b481c057/zoom-alphafly-next-nature-zapatillas-de-competicion-carretera-3mk9g2.png`,
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/d2667e1c-3585-45b9-a979-47485280b90e/zoom-alphafly-next-nature-zapatillas-de-competicion-carretera-3mk9g2.png",
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/8f7b5836-27ec-4248-aea0-688d9652aaca/zoom-alphafly-next-nature-zapatillas-de-competicion-carretera-3mk9g2.png",
        ],
        description:
            "Dalo todo para llegar a la meta con el siguiente paso en nuestro camino de sostenibilidad.Hemos confeccionado las ultraligeras Nike Air Zoom Alphafly Next Nature con, al menos, un 50 % de materiales reciclados por peso y que no reducen el rendimiento.Se han diseñado para mejorar tus récords personales con un diseño seguro, transpirable y tan ligero que ofrece la sensación de volar.Has entrenado duro, ponte las zapatillas y dalo todo con unas zapatillas confeccionadas con residuos.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Nike",
        genre: "Man",
        title: "Nike ZoomX Vaporfly Next% 2",
        price: 249,
        img: [
            `https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/1622d34a-b828-4483-a974-74ca66bfb8b5/zoomx-vaporfly-next-2-zapatillas-de-competicion-asfalto-821S4F.png`,
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/ce4e493a-b8b2-47a5-b1ee-e8e3ef63029e/zoomx-vaporfly-next-2-zapatillas-de-competicion-asfalto-821S4F.png",
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/5cfa0cf1-dbf5-48a0-9ede-bcc60fe5daec/zoomx-vaporfly-next-2-zapatillas-de-competicion-asfalto-821S4F.png",
        ],
        description:
            "Descubre la siguiente evolución de la velocidad con unas zapatillas de competición diseñadas para perseguir nuevos objetivos y récords. Ayudan a mejorar la comodidad y la transpirabilidad con una parte superior rediseñada. Ya sea en carreras de 10 kilómetros o en maratones, este modelo, al igual que su versión anterior, ofrece una amortiguación reactiva y una sujeción segura para superar cualquier marca personal.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Adidas",
        genre: "Man",
        title: "Zapatilla Gazelle",
        price: 95,
        img: [
            `https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a847e062376346299a7ca80200807c9c_9366/Zapatilla_Gazelle_Gris_BB5480_01_standard.jpg`,
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/35b62c08f4f840f59c35a8020080a891_9366/Zapatilla_Gazelle_Gris_BB5480_04_standard.jpg",
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/ab0b1dac0a1641c080e0a8020080b395_9366/Zapatilla_Gazelle_Gris_BB5480_05_standard.jpg",
        ],
        description:
            "Un auténtico clásico. Tras debutar como una zapatilla esencialmente deportiva, la Gazelle no tardó en convertirse en un icono del estilo urbano. Esta zapatilla se ha confeccionado con los mismos materiales, colores y proporciones ligeramente más anchas que la versión de 1991. Presenta una parte superior de nobuk suave que le aporta un aire sofisticado.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Adidas",
        genre: "Man",
        title: "Zapatilla Adizero adios 6",
        price: 130,
        img: [
            `https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/4c4b6ffd447d4458baafad75010f999b_9366/Zapatilla_Adizero_Adios_6_Azul_GY0893_01_standard.jpg`,
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/58043ddafa2f4275ba45ad750125740b_9366/Zapatilla_Adizero_Adios_6_Azul_GY0893_04_standard.jpg",
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9584acb7ea67487fb6eaad7501257c10_9366/Zapatilla_Adizero_Adios_6_Azul_GY0893_05_standard.jpg",
        ],
        description:
            "Esta zapatilla de running adidas es perfecta para una carrera de 5 kilómetros o una media maratón. Incorpora la tecnología Lightstrike Pro bajo el antepié que ayuda a reducir la fatiga mientras compites o entrenas. Las varillas Torsion añaden una mayor ligereza, rigidez e impulso en cada zancada.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Adidas",
        genre: "Man",
        title: "Zapatilla Retropy F2",
        price: 100,
        img: [
            `https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/2ab8276800c2430e824dadf4000be2a8_9366/Zapatilla_Retropy_F2_Blanco_GW5473_01_standard.jpg`,
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/55dc577c03ed4bdc8bddadf4000b010e_9366/Zapatilla_Retropy_F2_Blanco_GW5473_04_standard.jpg",
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/578fad83d7b24553b2f3adf40009d29b_9366/Zapatilla_Retropy_F2_Blanco_GW5473_05_standard.jpg",
        ],
        description:
            "Siempre te ha gustado ir un paso por delante. La zapatilla adidas Retropy F2 es la combinación perfecta de detalles vintage y un diseño actual. La parte superior que combina diferentes materiales se inspira en el estilo del running. Su silueta estilizada y la mediasuela gruesa de EVA la hacen perfecta para las calles de hoy.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Adidas",
        genre: "Man",
        title: "Zapatilla Ultraboost 5.0 DNA",
        price: 180,
        img: [
            `https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/6ca23fdb02c0443c9cc7ade201877e09_9366/Zapatilla_Ultraboost_5.0_DNA_Azul_GY7952_01_standard.jpg`,
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/e1291c06e41944aa890aade20186d56c_9366/Zapatilla_Ultraboost_5.0_DNA_Azul_GY7952_04_standard.jpg",
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/7bcc3fa2b012451780ffade20185be49_9366/Zapatilla_Ultraboost_5.0_DNA_Azul_GY7952_05_standard.jpg",
        ],
        description:
            "Siempre es un buen momento para ponerse la adidas Ultraboost. Esta versión cuenta con la tecnología que más gusta a los corredores y se actualiza con un toque metalizado. La mediasuela con tecnología BOOST y la parte superior de suave tejido adidas PRIMEKNIT garantizan una combinación perfecta de energía, sujeción y flexibilidad.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Adidas",
        genre: "Man",
        title: "Zapatilla Superstar",
        price: 100,
        img: [
            `https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a2a7c4914823434b9ff7adc5017672c5_9366/Zapatilla_Superstar_Blanco_GZ1603_01_standard.jpg`,
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/8b8cb29cb7ef48a09feeadc501759316_9366/Zapatilla_Superstar_Blanco_GZ1603_04_standard.jpg",
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c7f21a04919c4260b5b7adc501748057_9366/Zapatilla_Superstar_Blanco_GZ1603_05_standard.jpg",
        ],
        description:
            "Brilla con luz propia con esta zapatilla adidas Superstar. Cuenta con paneles reflectantes que te permiten destacar en la pista de baile o en un día gris en la ciudad. La parte superior de piel suave, la mítica puntera y la suela de goma son el sello del genuino estilo de adidas. Póntela y sal a la calle.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Puma",
        genre: "Man",
        title: "Zapatillas CA Pro Classic",
        price: 90,
        img: [
            `https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380190/03/sv01/fnd/EEA/fmt/png/Zapatillas-CA-Pro-Classic.jpg`,
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380190/03/fnd/EEA/fmt/png/Zapatillas-CA-Pro-Classic.jpg",
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380190/03/sv04/fnd/EEA/fmt/png/Zapatillas-CA-Pro-Classic.jpg",
        ],
        description:
            "La California original de PUMA ha estado dejando su huella en las calles desde que se lanzó en los años 80. Las zapatillas CA Pro Classic, la nueva incorporación a esta familia del calzado, incorporan todos los elementos clave del diseño emblemático, como las líneas sencillas, pero con el añadido de perforaciones y una entresuela moldeada.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Puma",
        genre: "Man",
        title: "Zapatillas Mirage Sport Tech",
        price: 90,
        img: [
            `https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/383107/05/sv01/fnd/EEA/fmt/png/Zapatillas-Mirage-Sport-Tech.jpg`,
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/383107/05/fnd/EEA/fmt/png/Zapatillas-Mirage-Sport-Tech.jpg",
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/383107/05/sv04/fnd/EEA/fmt/png/Zapatillas-Mirage-Sport-Tech.jpg",
        ],
        description:
            "Celebradas durante mucho tiempo por su ligereza, estabilidad y comodidad, las zapatillas Mirage Sport Tech regresan de los archivos de los 90 con un diseño nuevo y actual. Inspirada en la cultura DJ, con un diseño futurista que explora líneas progresivas y un increíble aire urbano, esta llamativa versión cuenta con un exterior de malla con capas superpuestas sintéticas y por termofusión, costuras destacadas, elementos atrevidos de marca y un diseño elegante. Estas zapatillas yuxtaponen lo clásico y lo deportivo para marcar tendencia y acaparar todas las miradas.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Puma",
        genre: "Man",
        title: "Zapatillas City Rider Moulded",
        price: 90,
        img: [
            `https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/383411/03/sv01/fnd/EEA/fmt/png/Zapatillas-City-Rider-Moulded.jpg`,
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/383411/03/fnd/EEA/fmt/png/Zapatillas-City-Rider-Moulded.jpg",
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/383411/03/sv04/fnd/EEA/fmt/png/Zapatillas-City-Rider-Moulded.jpg",
        ],
        description:
            "Haz olas con las impresionantes líneas y el espectacular diseño de nuestras City Rider Moulded Trainers, una zapatilla de deporte Futro que combina la suela exterior Rider con materiales y colores impresionantes que te ayudan a pasar de la calle a los senderos con facilidad. Esta elegante zapatilla añade el acento atlético perfecto a cualquier conjunto.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Puma",
        genre: "Man",
        title: "Zapatillas Future Rider Play On",
        price: 95,
        img: [
            `https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/371149/75/sv01/fnd/EEA/fmt/png/Zapatillas-Future-Rider-Play-On.jpg`,
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/371149/75/fnd/EEA/fmt/png/Zapatillas-Future-Rider-Play-On.jpg",
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/371149/75/sv04/fnd/EEA/fmt/png/Zapatillas-Future-Rider-Play-On.jpg",
        ],
        description:
            "Mantén vivo el legado de un calzado que inició un movimiento: las Rider Play On. Estas zapatillas se centran en ofrecerte el rendimiento más puro, con un exterior superligero de nailon y nuestra famosa suela Federbein, que absorbe los impactos para que pises con estilo.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Puma",
        genre: "Man",
        title: "Zapatillas RS-Fast Limiter",
        price: 110,
        img: [
            `https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/385043/01/sv01/fnd/EEA/fmt/png/Zapatillas-RS-Fast-Limiter.jpg`,
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/385043/01/fnd/EEA/fmt/png/Zapatillas-RS-Fast-Limiter.jpg",
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/385043/01/sv04/fnd/EEA/fmt/png/Zapatillas-RS-Fast-Limiter.jpg",
        ],
        description:
            "Son rápidas. Son modernas. Son una nueva versión del modelo RS. Estas zapatillas, que combinan un diseño inspirado en los principios de la década de los 2000, atrevidos detalles de marca, gráficos sorprendentes, colores modernos y un aire futurista para representar a los nativos digitales de hoy en día, están listas para que alcances nuevas cotas de estilo. Con corazones tachonados en el empeine y detalles técnicos en el talón, este modelo representa el estilo PUMA más puro.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Reebok",
        genre: "Man",
        title: "Classic Leather",
        price: 90,
        img: [
            `https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/82990a1fa28143259f57add8003228f2_9366/Classic_Leather_Blanco_GX6196_01_standard.jpg`,
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/636d9ee71c9a44df8dd0add8002e7ce0_9366/Classic_Leather_Blanco_GX6196_03_standard.jpg",
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/4e6955b9fdbe4c14a446add80036c453_9366/Classic_Leather_Blanco_GX6196_04_standard.jpg",
        ],
        description:
            "Esta Reebok Classic Leather permanece fiel a los principios de la artesanía tradicional, aunque inspirándose en el diseño de los artesanos modernos. Redefine el concepto de 'ropa de trabajo' con este modelo de zapatilla. La parte superior tiene un look deconstruido que reimagina el modelo original.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Reebok",
        genre: "Man",
        title: "Floatride Energy Grow",
        price: 120,
        img: [
            `https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3b8d5831761a44b8a818ad1f014604b0_9366/Floatride_Energy_Grow_Verde_GZ7574_01_standard.jpg`,
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/18081f8d554b4e758154ad1f0145d3f8_9366/Floatride_Energy_Grow_Verde_GZ7574_03_standard.jpg",
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/06ce64dd77f74b3ab0aead1f0145ec21_9366/Floatride_Energy_Grow_Verde_GZ7574_04_standard.jpg",
        ],
        description:
            "Siéntete tan bien por dentro como por fuera cuando salgas a correr con esta zapatilla de running para hombre hecha con materiales a base de plantas. La espuma Floaride Energy está hecha con aceite de ricino y te ofrece una amortiguación ligera y una alta capacidad de respuesta en cada pisada. El talón acampanado reduce la presión sobre el tendón de Aquiles para un mayor confort.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Reebok",
        genre: "Man",
        title: "Reebok Nano X2",
        price: 130,
        img: [
            `https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/e45a35ba46304314b6b7ade800aaaaac_9366/Reebok_Nano_X2_Negro_GZ6435_01_standard.jpg`,
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/551bf16dba0f4a1b9eecade800aa9a8a_9366/Reebok_Nano_X2_Negro_GZ6435_03_standard.jpg",
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/f86fc3bf6acd4a89b69eade800aaa25d_9366/Reebok_Nano_X2_Negro_GZ6435_04_standard.jpg",
        ],
        description:
            "Desde pistols hasta burpees, domina todos los movimientos que llevarán tu entrenamiento al siguiente nivel. Ponte esta zapatilla Reebok para hombre y mantente cómodo y seguro dentro y fuera del gym. La parte superior de tejido Flexweave® es transpirable y resistente, y cuenta con sujeción integrada para movimientos estables en todas las direcciones. La suela de caucho con patrón de tacos en zonas estratégicas te proporciona una tracción óptima.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Reebok",
        genre: "Man",
        title: "Classic Leather Legacy",
        price: 90,
        img: [
            `https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/e1fed1eb44e147359eb7ac7c0144fc6d_9366/Classic_Leather_Legacy_Verde_FY7560_01_standard.jpg`,
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/111f99deb9a745b6b1d6ac7c01415a8a_9366/Classic_Leather_Legacy_Verde_FY7560_03_standard.jpg",
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/98acf76b776e4cd8927dac7c0148e661_9366/Classic_Leather_Legacy_Verde_FY7560_04_standard.jpg",
        ],
        description:
            "Toma nota. El estilo Reebok vintage envejece muy bien. Pero eso es algo que ya sabías. Simplemente mira esta zapatilla Reebok retro. En caso de que su look original con la parte superior de nobuk y tela no sea suficiente para ti, dale la vuelta y revisa el diseño de malla con la suela de caucho de color caramelo en contraste. No está mal, ¿no?",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Reebok",
        genre: "Man",
        title: "Club C 85",
        price: 90,
        img: [
            `https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/20b7c28a3fea4cc68baeadea015f0be2_9366/Club_C_85_Blanco_GZ1605_01_standard.jpg`,
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3fa028c8c56f4d5a9529adea0156d886_9366/Club_C_85_Blanco_GZ1605_03_standard.jpg",
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9d97dbb1cfe1472ea0c7adea015c4c79_9366/Club_C_85_Blanco_GZ1605_04_standard.jpg",
        ],
        description:
            "Fluye a cada paso. Esta zapatilla lo hace contigo. Cálzate esta Club C 85 y marca tendencia. El estilo sencillo de esta zapatilla de piel suave combina a la perfección con todo tu armario. Porque a veces no hace falta decir nada para lanzar un mensaje claro.",
        units: 10,
        sizes: "39, 40, 41, 42, 43, 44",
        value: 0,
    },
    {
        brand: "Nike",
        genre: "Woman",
        title: "Nike Zoom Alphafly Next Nature",
        price: 290,
        img: [
            `https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/04993055-6221-4a74-8ff2-bd37b481c057/zoom-alphafly-next-nature-zapatillas-de-competicion-carretera-3mk9g2.png`,
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/d2667e1c-3585-45b9-a979-47485280b90e/zoom-alphafly-next-nature-zapatillas-de-competicion-carretera-3mk9g2.png",
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/8f7b5836-27ec-4248-aea0-688d9652aaca/zoom-alphafly-next-nature-zapatillas-de-competicion-carretera-3mk9g2.png",
        ],
        description:
            "Dalo todo para llegar a la meta con el siguiente paso en nuestro camino de sostenibilidad.Hemos confeccionado las ultraligeras Nike Air Zoom Alphafly Next Nature con, al menos, un 50 % de materiales reciclados por peso y que no reducen el rendimiento.Se han diseñado para mejorar tus récords personales con un diseño seguro, transpirable y tan ligero que ofrece la sensación de volar.Has entrenado duro, ponte las zapatillas y dalo todo con unas zapatillas confeccionadas con residuos.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Nike",
        genre: "Woman",
        title: "Nike Metcon 7",
        price: 127,
        img: [
            `https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/033783c5-accf-4ec1-b554-0fb198833915/metcon-7-zapatillas-de-entrenamiento-CHLK3h.png`,
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/f7a76627-e25a-4172-92d3-3f3d3867ea8a/metcon-7-zapatillas-de-entrenamiento-CHLK3h.png",
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/1a4d8894-545f-42d2-b2bb-5d5f6eb1d69a/metcon-7-zapatillas-de-entrenamiento-CHLK3h.png",
        ],
        description:
            "Las Nike Metcon 7 son ideales para el entrenamiento con pesas, y ofrecen un estilo más resistente y estable que en las versiones anteriores.Además, hemos añadido espuma React que mejora la comodidad para prepararte para los entrenamientos de alta intensidad.Además, cuenta con una presilla que sujeta los cordones para que puedas olvidarte de atarlos cuando te centras en batir tu récord personal.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Nike",
        genre: "Woman",
        title: "Air Force 1 Low - Be Kind",
        price: 129,
        img: [
            `https://static.nike.com/a/images/t_prod_ss/w_640,c_limit,f_auto/c391759b-7fb3-44cc-8a36-6b6bf234c204/fecha-de-lanzamiento-de-las-air-force-1-low-be-kind-para-mujer-dr3100-001.jpg`,
            "https://static.nike.com/a/images/t_prod_sc/w_640,c_limit,f_auto/e206abfa-97c3-4a5b-bd82-a6e257c22d20/fecha-de-lanzamiento-de-las-air-force-1-low-be-kind-para-mujer-dr3100-001.jpg",
            "https://static.nike.com/a/images/t_prod_ss/w_640,c_limit,f_auto/7b016720-d4dc-461b-ad9b-243892d0fc7f/fecha-de-lanzamiento-de-las-air-force-1-low-be-kind-para-mujer-dr3100-001.jpg",
        ],
        description:
            "Veámoslas con calma. Con unos agradables e innovadores colores como el aura, el light iron ore y el ocean cube, estas Air Force 1 Low desprenden un estilo apacible cargado de sensibilidad. Los pespuntes a la vista y los materiales combinados como el ante y la piel rugosa añaden un toque premium al aire discreto de este icono urbano. Justo bajo la presilla del talón, hay un mensaje para cualquier persona que necesite este sencillo consejo con el que se puede llegar muy lejos en la vida: 'Be Kind'.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Nike",
        genre: "Woman",
        title: "Nike Air Max Dawn",
        price: 114,
        img: [
            `https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/e23bface-a9c1-461b-9217-f49d8de91b7d/air-max-dawn-zapatillas-k5w0QL.png`,
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/361b7848-9a68-4cda-bd6d-9c12d6d5bc14/air-max-dawn-zapatillas-k5w0QL.png",
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/32052ac6-835e-4e0e-aa69-0329950b8af4/air-max-dawn-zapatillas-k5w0QL.png",
        ],
        description:
            "Con un diseño inspirado en el ADN deportivo, las Air Max Dawn se han confeccionado con, al menos, un 20 % de contenido reciclado por peso. Las líneas gráficas y el diseño Color Block aportan una nueva actualización inspirada en el jogakbo o el patchwork, técnicas que se utilizan a menudo en el tradicional arte textil coreano de bojagi. El ante sintético suave, los tejidos transpirables y las unidades Max Air del talón hacen que estas zapatillas sean fieles a sus raíces de running vintage. Al ponértelas, experimentarás un nuevo amanecer.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Nike",
        genre: "Woman",
        title: "Nike Air Max 270",
        price: 149,
        img: [
            `https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/1b8e8e0e-acdd-429a-986c-24ccb2254d05/air-max-270-zapatillas-P0j2DN.png`,
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/d4b051cb-f9bc-4d85-a4f9-299f85ffcc90/air-max-270-zapatillas-P0j2DN.png",
            "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/3b761920-a1bc-442c-b04d-6eafabc87e10/air-max-270-zapatillas-P0j2DN.png",
        ],
        description:
            "Las primeras Air Max de Nike para el día a día ofrecen más estilo, comodidad y una gran actitud en las Nike Air Max 270. El diseño se inspira en los iconos de Air Max para destacar la innovación más importante de Nike con una amplia ventana y una gran variedad de colores modernos.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Adidas",
        genre: "Woman",
        title: "Zapatilla Ultraboost 22",
        price: 180,
        img: [
            `https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/798d3061f5934cd1983bade800a7f2dd_9366/ZAPATILLA_ULTRABOOST_22_Blanco_GX5595_01_standard.jpg`,
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/616ba20c88d742909a7dade500f6a6fb_9366/ZAPATILLA_ULTRABOOST_22_Blanco_GX5595_04_standard.jpg",
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/7c6fde21e28743818a74ade800a81553_9366/ZAPATILLA_ULTRABOOST_22_Blanco_GX5595_05_standard.jpg",
        ],
        description:
            "Hemos analizado 1.200.000 pisadas para que Ultraboost evolucione y mejore su ajuste para adaptarse 360° al pie femenino. Y lo que es aún mejor. Hemos rediseñado la suela de caucho y hemos probado cientos de prototipos hasta que hemos garantizado un mejor rendimiento.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Adidas",
        genre: "Woman",
        title: "Zapatilla ZX 2K Boost 2.0",
        price: 140,
        img: [
            `https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/550c55c33cf44016a3a3ad2100c42d25_9366/Zapatilla_ZX_2K_Boost_2.0_Blanco_GZ7741_01_standard.jpg`,
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/ed5bd9db703a4f26abfdad2100c448d3_9366/Zapatilla_ZX_2K_Boost_2.0_Blanco_GZ7741_04_standard.jpg",
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/65d80f89503d4efe8097ad2100c44fc4_9366/Zapatilla_ZX_2K_Boost_2.0_Blanco_GZ7741_05_standard.jpg",
        ],
        description:
            "La saga adidas ZX revolucionó el mundo del running en los 80 por su diseño técnico y su espíritu vanguardista. Hoy nada ha cambiado. Esta zapatilla incorpora la tecnología Boost que te brinda una gran amortiguación y comodidad en los días de máxima actividad.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Adidas",
        genre: "Woman",
        title: "Zapatilla Ozweego",
        price: 120,
        img: [
            `https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3aa509532b4c4294a4c3ad7401161f97_9366/Zapatilla_OZWEEGO_Beige_GW5620_01_standard.jpg`,
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/24043e7857474a47a44bad7401163d65_9366/Zapatilla_OZWEEGO_Beige_GW5620_04_standard.jpg",
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/ffd3c24a906a44dab4c7ad7401164594_9366/Zapatilla_OZWEEGO_Beige_GW5620_05_standard.jpg",
        ],
        description:
            "El estilo de los 90 con un enfoque futurista. Esta zapatilla adidas OZWEEGO presenta un diseño acolchado con elementos vintage de nuestros archivos. Un poco retro, muy moderna y tan cómoda que querrás dormir con ella.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Adidas",
        genre: "Woman",
        title: "Zapatilla Retropy P9",
        price: 160,
        img: [
            `https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/252b7060b9ca4dc592ebad330105d4f8_9366/Zapatilla_Retropy_P9_Negro_H03085_01_standard.jpg`,
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/2a5ad7c77b504e92969ead330105ec6d_9366/Zapatilla_Retropy_P9_Negro_H03085_04_standard.jpg",
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/75c5637d6dbb45ea95fdad330105f2e1_9366/Zapatilla_Retropy_P9_Negro_H03085_05_standard.jpg",
        ],
        description:
            "Cada década es recordada por algo. ¿Los años 80? Por su estilo colorido y llamativo. ¿Los años 2000? Por las innovaciones tecnológicas. Esta zapatilla adidas fusiona lo mejor de ambas eras. La silueta de inspiración retro y la tecnología de amortiguación Boost se combinan para crear un diseño nuevo y actual.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Adidas",
        genre: "Woman",
        title: "Zapatilla Solarglide 5",
        price: 140,
        img: [
            `https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/799215b001d54608900eadf800895169_9366/Zapatilla_Solarglide_5_Blanco_GX5496_01_standard.jpg`,
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/f6d9f200c4374c8ab65dadf800897589_9366/Zapatilla_Solarglide_5_Blanco_GX5496_04_standard.jpg",
            "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/fb6759513b5e46df9e3cadf800897ed6_9366/Zapatilla_Solarglide_5_Blanco_GX5496_05_standard.jpg",
        ],
        description:
            "Ya sea para mejorar tu forma física, sumar kilómetros o mejorar tu marca personal, esta zapatilla de running Solarglide 5 de adidas se adapta a todos tus objetivos de carrera. Combina una parte superior de punto y una mediasuela BOOST con sistema adidas LEP 2.0 que proporciona un retorno de energía increíble y una estabilidad superior. Esta zapatilla presenta una parte superior fabricada con un hilo de alto rendimiento creado con al menos un 50% de Parley Ocean Plastic, un material reciclado a partir de residuos plásticos recogidos en zonas costeras para evitar que contaminen nuestros océanos.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Puma",
        genre: "Woman",
        title: "Cruise Rider Tumbled VG",
        price: 100,
        img: [
            `https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/384446/01/sv01/fnd/EEA/fmt/png/Zapatillas-para-mujer-PUMA-x-PAMELA-REIF-Cruise-Rider-Tumbled-VG.jpg`,
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/384446/01/fnd/EEA/fmt/png/Zapatillas-para-mujer-PUMA-x-PAMELA-REIF-Cruise-Rider-Tumbled-VG.jpg",
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/384446/01/sv04/fnd/EEA/fmt/png/Zapatillas-para-mujer-PUMA-x-PAMELA-REIF-Cruise-Rider-Tumbled-VG.jpg",
        ],
        description:
            "Pon tu estilo a tope con esta última incorporación a la familia Cruse Rider. Las PUMA x PAMELA REIF Cruise Rider Tumbled VG Trainers son para los atrevidos y rebeldes. Tanto la parte superior como la suela se mantienen fieles al linaje de las Rider, mientras que los adornos tácticos son perfectos para los días que pasas en la ciudad.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Puma",
        genre: "Woman",
        title: "Suede Mayu Raw",
        price: 110,
        img: [
            `https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/383114/03/sv01/fnd/EEA/fmt/png/Zapatillas-para-mujer-Suede-Mayu-Raw.jpg`,
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/383114/03/fnd/EEA/fmt/png/Zapatillas-para-mujer-Suede-Mayu-Raw.jpg",
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/383114/03/sv04/fnd/EEA/fmt/png/Zapatillas-para-mujer-Suede-Mayu-Raw.jpg",
        ],
        description:
            "Esta versión vanguardista de las emblemáticas zapatillas Suede es un poco tosca y así es como nos gusta. Este modelo Mayu juega con unas proporciones exageradas para crear una silueta totalmente propia, mientras que los bordes sin rematar de los detalles de ante le confieren un aspecto deconstruido. La moderna marca PUMA estampada en 3D también le aporta un aire vanguardista. El clásico modelo Suede de PUMA con un nuevo estilo sin refinar.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Puma",
        genre: "Woman",
        title: "Future Rider Displaced",
        price: 90,
        img: [
            `https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/383148/07/sv01/fnd/EEA/fmt/png/Zapatillas-Future-Rider-Displaced.jpg`,
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/383148/07/fnd/EEA/fmt/png/Zapatillas-Future-Rider-Displaced.jpg",
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/383148/07/sv04/fnd/EEA/fmt/png/Zapatillas-Future-Rider-Displaced.jpg",
        ],
        description:
            "Nuestra colección Future Rider, una incorporación sorprendente a nuestra familia de zapatillas Rider inspirada en la tecnología, va a hacer que te replantees el concepto de “posible”. Nuestras zapatillas Future Rider Displaced innovan sobre el modelo clásico Rider, al que añaden sorprendentes detalles degradados, un exterior deportivo de líneas depuradas y la máxima comodidad de la entresuela IMEVA, que ofrece una zancada ligera y un retorno de la energía increíble a cada paso.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Puma",
        genre: "Woman",
        title: "Cruise Rider",
        price: 69,
        img: [
            `https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/375072/30/sv01/fnd/EEA/fmt/png/Zapatillas-Cruise-Rider-para-mujer.jpg`,
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/375072/30/fnd/EEA/fmt/png/Zapatillas-Cruise-Rider-para-mujer.jpg",
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/375072/30/sv04/fnd/EEA/fmt/png/Zapatillas-Cruise-Rider-para-mujer.jpg",
        ],
        description:
            "Inspiradas en la belleza de las famosas Silk Road, estas zapatillas incluyen combinaciones de colores que crean un look muy original. La entresuela IMEVA te brinda liviandad y comodidad para que tus pies sean felices.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Puma",
        genre: "Woman",
        title: "Suede Mayu",
        price: 100,
        img: [
            `https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380686/11/sv01/fnd/EEA/fmt/png/Zapatillas-para-mujer-Suede-Mayu.jpg`,
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380686/11/fnd/EEA/fmt/png/Zapatillas-para-mujer-Suede-Mayu.jpg",
            "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380686/11/sv04/fnd/EEA/fmt/png/Zapatillas-para-mujer-Suede-Mayu.jpg",
        ],
        description:
            "Las Mayu son la actualización de un clásico que lleva el estilo urbano a un nuevo nivel con una serie de detalles de diseño marcadamente futuristas. La llamativa suela envolvente de plataforma juega con las proporciones emblemáticas del legendario diseño Suede, lo que da como resultado un look irreverente que se puede llevar a diario. Por supuesto, son modernas y cómodas, pero el exterior de ante prémium y la marca PUMA metalizada las convierten en extraordinarias. Tan atemporales como actuales.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Reebok",
        genre: "Woman",
        title: "Classic Leather",
        price: 90,
        img: [
            `https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/82990a1fa28143259f57add8003228f2_9366/Classic_Leather_Blanco_GX6196_01_standard.jpg`,
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/636d9ee71c9a44df8dd0add8002e7ce0_9366/Classic_Leather_Blanco_GX6196_03_standard.jpg",
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/4e6955b9fdbe4c14a446add80036c453_9366/Classic_Leather_Blanco_GX6196_04_standard.jpg",
        ],
        description:
            "Esta Reebok Classic Leather permanece fiel a los principios de la artesanía tradicional, aunque inspirándose en el diseño de los artesanos modernos. Redefine el concepto de 'ropa de trabajo' con este modelo de zapatilla. La parte superior tiene un look deconstruido que reimagina el modelo original.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Reebok",
        genre: "Woman",
        title: "Club C Clean",
        price: 110,
        img: [
            `https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/83bcfb9fdafb4d9c8588adc501846864_9366/Club_C_Clean_Blanco_GW5114_01_standard.jpg`,
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/5ef662f91a0e444ab178adc5018183c2_9366/Club_C_Clean_Blanco_GW5114_03_standard.jpg",
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/4a45834de34c449a8614adc50189c162_9366/Club_C_Clean_Blanco_GW5114_04_standard.jpg",
        ],
        description:
            "No necesitas cambiar de zapatillas. Ponte esta Reebok Club C Clean con unos vaqueros o tu look de trabajo y luce un look impecable y minimalista para ir a cualquier parte. La paleta de colores neutros te permite combinarla fácilmente. Porque lo simple también es chic.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Reebok",
        genre: "Woman",
        title: "Nano X1 Adventure",
        price: 130,
        img: [
            `https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/bb08902d326b43159e70ae550060d8f0_9366/Nano_X1_Adventure_Violeta_GY8442_01_standard.jpg`,
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/040f5128a4344ee68973ae5500634a42_9366/Nano_X1_Adventure_Violeta_GY8442_03_standard.jpg",
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/ce52d7ceae2944fd8b0aae55005f9432_9366/Nano_X1_Adventure_Violeta_GY8442_04_standard.jpg",
        ],
        description:
            "Ya sea para hacer un entrenamiento boot camp en el parque o ejercicios con peso corporal en medio de la naturaleza, con esta zapatilla de training para mujer te divertirás más que nunca entrenando al aire libre. La espuma Floatride Energy en la puntera te proporciona una sensación ligera y una pisada reactiva. La suela con tacos pronunciados te garantiza agarre en los box jumps.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Reebok",
        genre: "Woman",
        title: "Classic Leather Legacy",
        price: 90,
        img: [
            `https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/e1fed1eb44e147359eb7ac7c0144fc6d_9366/Classic_Leather_Legacy_Verde_FY7560_01_standard.jpg`,
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/111f99deb9a745b6b1d6ac7c01415a8a_9366/Classic_Leather_Legacy_Verde_FY7560_03_standard.jpg",
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/98acf76b776e4cd8927dac7c0148e661_9366/Classic_Leather_Legacy_Verde_FY7560_04_standard.jpg",
        ],
        description:
            "Toma nota. El estilo Reebok vintage envejece muy bien. Pero eso es algo que ya sabías. Simplemente mira esta zapatilla Reebok retro. En caso de que su look original con la parte superior de nobuk y tela no sea suficiente para ti, dale la vuelta y revisa el diseño de malla con la suela de caucho de color caramelo en contraste. No está mal, ¿no?",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
    {
        brand: "Reebok",
        genre: "Woman",
        title: "Club C 85 Vintage",
        price: 110,
        img: [
            `https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/833fd67a367243989f55ae4c0017e4eb_9366/Club_C_85_Vintage_Blanco_GX3686_01_standard.jpg`,
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/203b0bb1b8844a1ba420ae4c0018d37e_9366/Club_C_85_Vintage_Blanco_GX3686_03_standard.jpg",
            "https://assets.reebok.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/56905a8fd8004b23be7cae4c0016aadb_9366/Club_C_85_Vintage_Blanco_GX3686_04_standard.jpg",
        ],
        description:
            "Simple y minimalista. Con este modelo inspirado en las pistas de tenis lucirás un look simple e impecable. Viene con detalles sutiles en contraste que aportan un toque elegante. La ventana con el logo Reebok y la Union Jack le infunde un look de la vieja escuela. La parte superior está hecha de piel suave y flexible.",
        units: 10,
        sizes: "36, 37, 38, 39, 40, 41",
        value: 0,
    },
];

export { data };
